name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Run tests
        run: npm test
